"""
Key and mouse mappings from pynput input codes to pyautogui codes.

Allows MacroPlayer to replay MacroRecorder's recordings.

"""

key_map = {
    "Key.alt": "alt",
    "Key.alt_l": "altleft",
    "Key.alt_r": "altright",
    "Key.ctrl": "ctrl",
    "Key.ctrl_l": "ctrlleft",
    "Key.ctrl_r": "ctrlright",
    "Key.shift": "shift",
    "Key.shift_l": "shiftleft",
    "Key.shift_r": "shiftright",
    "Key.cmd": "win",
    "Key.cmd_l": "winleft",
    "Key.cmd_r": "winright",
    "Key.space": "space",
    "Key.enter": "enter",
    "Key.tab": "tab",
    "Key.backspace": "backspace",
    "Key.delete": "del",
    "Key.esc": "esc",
    "Key.caps_lock": "capslock",
    "Key.f1": "f1",
    "Key.f2": "f2",
    "Key.f3": "f3",
    "Key.f4": "f4",
    "Key.f5": "f5",
    "Key.f6": "f6",
    "Key.f7": "f7",
    "Key.f8": "f8",
    "Key.f9": "f9",
    "Key.f10": "f10",
    "Key.f11": "f11",
    "Key.f12": "f12",
    "Key.print_screen": "printscreen",
    "Key.scroll_lock": "scrolllock",
    "Key.pause": "pause",
    "Key.insert": "insert",
    "Key.home": "home",
    "Key.end": "end",
    "Key.page_up": "pageup",
    "Key.page_down": "pagedown",
    "Key.up": "up",
    "Key.down": "down",
    "Key.left": "left",
    "Key.right": "right",
    "Key.num_lock": "numlock",
    "Key.keypad_0": "num0",
    "Key.keypad_1": "num1",
    "Key.keypad_2": "num2",
    "Key.keypad_3": "num3",
    "Key.keypad_4": "num4",
    "Key.keypad_5": "num5",
    "Key.keypad_6": "num6",
    "Key.keypad_7": "num7",
    "Key.keypad_8": "num8",
    "Key.keypad_9": "num9",
    "Key.keypad_add": "+",
    "Key.keypad_subtract": "-",
    "Key.keypad_multiply": "*",
    "Key.keypad_divide": "/",
    "Key.keypad_decimal": ".",
    "Key.keypad_enter": "enter",
    '\u0001': 'a',
    '\u0002': 'b',
    '\u0003': 'c',
    '\u0004': 'd',
    '\u0005': 'e',
    '\u0006': 'f',
    '\u0007': 'g',
    '\u0008': 'h',
    '\u0009': 'i',
    '\u000a': 'j',
    '\u000b': 'k',
    '\u000c': 'l',
    '\u000d': 'm',
    '\u000e': 'n',
    '\u000f': 'o',
    '\u0010': 'p',
    '\u0011': 'q',
    '\u0012': 'r',
    '\u0013': 's',
    '\u0014': 't',
    '\u0015': 'u',
    '\u0016': 'v',
    '\u0017': 'w',
    '\u0018': 'x',
    '\u0019': 'y',
    '\u001a': 'z',
}

mouse_button_map = {
    "Button.left": "left",
    "Button.right": "right",
    "Button.middle": "middle",
}
